import { readdir, readFile, mkdir, writeFile, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import ffmpeg from 'ffmpeg-static';

process.chdir(fileURLToPath(new URL('../', import.meta.url)));
const cachePath = 'ASSETS/music/loudness-cache.json';
const targetLufs = -18;
const peakCeilingDb = -2;
let previous = {};
try { previous = JSON.parse(await readFile(cachePath, 'utf8')); }
catch (error) { if (error.code !== 'ENOENT') throw error; }
const cache = {};
const gains = {};
async function scan(folder) {
  for (const entry of (await readdir(`ASSETS/${folder}`, { withFileTypes: true })).sort((a,b) => a.name.localeCompare(b.name))) {
    const key = `${folder}/${entry.name}`;
    if (entry.isDirectory()) { await scan(key); continue; }
    if (!/\.(mp3|ogg|wav|m4a|flac)$/i.test(entry.name)) continue;
    const source = `ASSETS/${key}`;
    const bytes = await readFile(source);
    const hash = createHash('sha256').update(bytes).digest('hex');
    let measurement = previous[key];
    if (measurement?.hash !== hash || !Number.isFinite(measurement.lufs) || !Number.isFinite(measurement.truePeakDb)) {
      console.log(`Measuring ${key}`);
      const result = spawnSync(ffmpeg, ['-hide_banner', '-nostats', '-i', source, '-vn', '-af', 'loudnorm=I=-18:TP=-2:print_format=json', '-f', 'null', '-'], { encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 });
      if (result.error || result.status !== 0) throw new Error(`FFmpeg failed for ${key}: ${result.error ?? result.stderr}`);
      const raw = JSON.parse(result.stderr.slice(result.stderr.lastIndexOf('{')));
      measurement = { hash, lufs: Number(raw.input_i), truePeakDb: Number(raw.input_tp) };
      if (!Number.isFinite(measurement.lufs) || !Number.isFinite(measurement.truePeakDb)) throw new Error(`Cannot measure ${key}`);
    }
    cache[key] = measurement;
    const gainDb = Math.min(targetLufs - measurement.lufs, peakCeilingDb - measurement.truePeakDb);
    gains[key] = Math.pow(10, gainDb / 20);
    const destination = `public/${key}`;
    await mkdir(path.dirname(destination), { recursive: true });
    let matches = false;
    try { matches = createHash('sha256').update(await readFile(destination)).digest('hex') === hash; }
    catch (error) { if (error.code !== 'ENOENT') throw error; }
    if (!matches) await copyFile(source, destination);
  }
}
await scan('music/Music-InGame');
await scan('music/Music-Menu');
await writeFile(cachePath, JSON.stringify(cache, null, 2) + '\n');
await writeFile('src/musicLoudness.ts', '// Generated by npm run music:scan. Do not edit.\nexport const MUSIC_LOUDNESS_GAINS: Record<string, number> = ' + JSON.stringify(gains, null, 2) + ';\n');
console.log(`Prepared ${Object.keys(gains).length} tracks at ${targetLufs} LUFS with a ${peakCeilingDb} dBTP ceiling (peak-limited tracks may remain quieter).`);
